language: ruby
cache: bundler
# Use the faster container based infrastructure
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

rvm:
  - 2.2
  - 2.3.6
  - 2.4
  - 2.5
  - ruby-head
  - jruby
  - rbx-2
  
before_install:
  - gem update --system

gemfile:
  - Gemfile
  - gemfiles/redisrb-master.gemfile

matrix:
  allow_failures:
    - rvm: rbx-2
